import { index, jsonb, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const orders = pgTable(
  "orders",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    orderNumber: text("order_number").notNull().unique(),
    productSlug: text("product_slug").notNull(),
    productLabel: text("product_label").notNull(),
    fulfillment: text("fulfillment").notNull().default("custom"),
    downloadUrl: text("download_url"),
    status: text("status").notNull().default("new"),
    business: text("business").notNull(),
    website: text("website").notNull(),
    city: text("city").notNull(),
    service: text("service").notNull(),
    platform: text("platform").notNull(),
    email: text("email").notNull(),
    phone: text("phone"),
    competitors: text("competitors"),
    pages: text("pages"),
    notes: text("notes"),
    source: text("source").notNull().default("intake_form"),
    metadata: jsonb("metadata").$type<Record<string, unknown>>().notNull().default({}),
    notificationStatus: text("notification_status").notNull().default("pending"),
    notificationError: text("notification_error"),
    customerNotificationStatus: text("customer_notification_status").notNull().default("pending"),
    customerNotificationError: text("customer_notification_error"),
    submittedAt: timestamp("submitted_at", { withTimezone: true }).notNull().defaultNow(),
    lastNotifiedAt: timestamp("last_notified_at", { withTimezone: true }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("orders_status_idx").on(table.status),
    index("orders_email_idx").on(table.email),
    index("orders_submitted_at_idx").on(table.submittedAt),
    index("orders_notification_status_idx").on(table.notificationStatus),
  ],
);
